### PR TITLE
testcases: add rteval

### PR DESCRIPTION
**Pull request by roxell**
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>

### CODE REVIEW

**Comment by mwasilew** [comment]
Is the 'master' template intended to allow customization in projects?

**Comment by roxell** [comment]
I didn't think about why I added it, I looked at ltp, kselftest, ssuite, kvm-unit-tests and did the same for this one.

**Comment by mwasilew** [comment]
It makes sense to have a 'master' template if you're planning to use multiple versions in tests. But if there is just going to be one, there is no need to carry 'master' template. That's why I asked.

**Comment by roxell** [comment]
aha understood, new version pushed without the master template...

**Pull request merged**
