### PR TITLE
Qemu arm cpu max

### PR DESCRIPTION
**Pull request by roxell**

### CODE REVIEW

**Review by nareshkamboju — APPROVED** [review]

**Comment by nareshkamboju** [comment]
Tested cpu max on qemu_arm64 LAVA jobs,
Linux version 5.13.0-rc7-next-20210622
 - https://lkft.validation.linaro.org/scheduler/job/2945653#L213

Linux version 5.4.128
 - https://lkft.validation.linaro.org/scheduler/job/2952157#L240

Linux version 4.4.273 
 - https://lkft.validation.linaro.org/scheduler/job/2952636#L225

**Comment by jscook2345** [comment]
Let's merge! (I don't have permission)

**Comment by bhcopeland** [comment]
Please don't push until you've ran the pipeline test @roxell

**Comment by nareshkamboju** [comment]
The Pipeline running this jobs is successful with cpu max on stable-rc 5.12.
https://lkft.validation.linaro.org/scheduler/job/2993067

**Comment by nareshkamboju** [comment]
Here is test pipeline,
https://gitlab.com/Linaro/lkft/users/anders.roxell/linux-stable/-/jobs/1394841702

**Comment by bhcopeland** [comment]
Can we add cpu MAX back in so it is ready to be pushed

**Review by bhcopeland — APPROVED** [review]

**Pull request merged**
