### PR TITLE
projects: lkft-android: include: Add defaults to metadata

### PR DESCRIPTION
**Pull request by stylesen**
Default to 'unknown' when a particular metadata parameter is unavailable.

### CODE REVIEW

**Comment by liuyq** [comment]
@stylesen thanks for the change! LGTM

**Comment by liuyq** [comment]
Hi, @roxell @bhcopeland 
when you are online could you please help check and merge if no issues there.

**Comment by bhcopeland** [comment]
I would go with `null` values when the value is unknown, then defining the word unknown. But apart from that LGTM

**Comment by bhcopeland** [comment]
@stylesen fair enough, lets push this through. Null should be set there, but lets keep it matched.

**Pull request merged**
