### PR TITLE
Creating armnn-benchmarking.yaml

### PR DESCRIPTION
**Pull request by K1504296**
armnn-ci-build: Creating armnn-benchmarking.yaml to run armnn mlperf benchmarking on debian devices.

### CODE REVIEW

**Comment by mwasilew** [comment]
Theo, could you package your test script as test definition and push here: https://github.com/Linaro/test-definitions? I was planning to do that for unit tests as well.

**Comment by mwasilew** [comment]
This looks good. Could you squash the commits (and force push)?

**Comment by mwasilew** [comment]
I guess for the basic example it's OK. We'll need ability to update parameters in the test.

**Comment by K1504296** [comment]
Yeah I think as the test is expanded it'll be important to remember to keep the parameters up to date; however, with only one device and minimal testing I didn't think it was necessary.

**Pull request merged**
