### PR TITLE
igt-gpu-tools: Adding tags chamelium for LAVA job template

### PR DESCRIPTION
**Pull request by nareshkamboju**
igt-gpu-tools: Adding tags chamelium for LAVA job template

Signed-off-by: Naresh Kamboju <naresh.kamboju@linaro.org>

### CODE REVIEW

**Comment by mrchapp** [comment]
+1 Looks good to me, but someone else must approve.

**Comment by roxell** [comment]
Please look for the keyword "TAGS" in master.jinja2 and in projects/lkft/variables.ini .

**Comment by roxell** [comment]
@nareshkamboju can we close this one?

**Comment by nareshkamboju** [comment]
@roxell agree with you closing this out.

**Pull request closed without merging**
