### PR TITLE
Db410c fix pre os command

### PR DESCRIPTION
**Pull request by roxell**

### CODE REVIEW

**Review by nareshkamboju — APPROVED** [review]

**Comment by nareshkamboju** [comment]
The selftests results looks good.
LGTM +1

**Comment by mwasilew** [comment]
I generated the templates for all devices with this patch. Hikey 6220 and hikey960 don't have the pre-os command after boot. This means there won't be any networking available. I guess this is a bug.

**Comment by roxell** [comment]
yes I guess so too, I'll solve it in the same PR

**Comment by mwasilew** [comment]
I feel adventurous today. Please report if it breaks anything.

**Pull request merged**
